import type { ConversationsData } from "@/types/conversation";

/**
 * Fonte de dados da tela Conversas.
 * Substitua por fetch à API (ex.: /api/workspaces/:slug/conversations).
 */
export async function getConversations(): Promise<ConversationsData> {
  return {
    workspace: {
      companyName: "Clínica Sol",
      userName: "João",
      userInitials: "JS",
    },
    notificationsCount: 3,
    conversations: [
      {
        id: "c1",
        leadName: "Mariana Costa",
        company: "TechNova",
        avatarInitials: "MC",
        lastMessage: "Podemos marcar para quinta às 15h?",
        lastMessageAt: "2026-08-04T20:42:00-03:00",
        channel: "whatsapp",
        status: "ai_handling",
        currentOwner: "sdr",
        unreadCount: 0,
        isTyping: null,
        opportunity: {
          leadName: "Mariana Costa",
          company: "TechNova",
          phone: "+55 11 98888-1122",
          email: "mariana@technova.com.br",
          source: "LinkedIn",
          temperature: "hot",
          pipelineStage: "Qualificação",
          currentOwner: "sdr",
          aiSummary:
            "Mariana é Head de RH da TechNova (180 funcionários). Interesse em automatizar prospecção outbound. Budget aprovado no trimestre. Preferência por reunião na quinta.",
          nextAction: "Confirmar reunião quinta 15h e enviar brief",
          lastActivity: "Há 12 min",
          meeting: {
            date: "07/08/2026",
            time: "15:00",
            link: "https://meet.google.com/abc-defg-hij",
            title: "Discovery — TechNova",
          },
          timeline: [
            { id: "t1", label: "Lead criado", timestamp: "01/08", done: true },
            { id: "t2", label: "Qualificado", timestamp: "03/08", done: true },
            {
              id: "t3",
              label: "Reunião marcada",
              timestamp: "04/08",
              done: true,
            },
            {
              id: "t4",
              label: "Negociação iniciada",
              timestamp: "—",
              done: false,
            },
          ],
        },
        messages: [
          {
            id: "m1",
            sender: "system",
            content: "SDR IA assumiu o atendimento.",
            timestamp: "2026-08-04T18:10:00-03:00",
            systemKind: "assumed",
          },
          {
            id: "m2",
            sender: "ai",
            content:
              "Olá Mariana! Sou a assistente comercial da Clínica Sol. Vi que você baixou o material sobre automação de vendas. Posso te ajudar a entender se faz sentido para a TechNova?",
            timestamp: "2026-08-04T18:10:30-03:00",
            status: "read",
            agentRole: "sdr",
          },
          {
            id: "m3",
            sender: "lead",
            content:
              "Oi! Sim, estamos avaliando ferramentas para outbound. Temos um time de 6 SDRs hoje.",
            timestamp: "2026-08-04T18:22:00-03:00",
            status: "read",
          },
          {
            id: "m4",
            sender: "ai",
            content:
              "Perfeito. Com 6 SDRs, o volume de follow-up e qualificação costuma ser o maior gargalo. Vocês já usam alguma ferramenta de sequenciamento?",
            timestamp: "2026-08-04T18:23:10-03:00",
            status: "read",
            agentRole: "sdr",
          },
          {
            id: "m5",
            sender: "lead",
            content: "Usamos só planilha e WhatsApp manual. Quero sair disso.",
            timestamp: "2026-08-04T19:05:00-03:00",
            status: "read",
          },
          {
            id: "m6",
            sender: "ai",
            content:
              "Entendi. Posso te mostrar em 20 minutos como a ForceIA opera o time inteiro — SDR, closer e follow-up — sem você configurar nada. Tem disponibilidade na quinta às 15h?",
            timestamp: "2026-08-04T19:06:20-03:00",
            status: "read",
            agentRole: "sdr",
          },
          {
            id: "m7",
            sender: "lead",
            content: "Podemos marcar para quinta às 15h?",
            timestamp: "2026-08-04T20:42:00-03:00",
            status: "read",
          },
          {
            id: "m8",
            sender: "system",
            content: "Reunião marcada para 07/08 às 15:00.",
            timestamp: "2026-08-04T20:42:30-03:00",
            systemKind: "meeting",
          },
        ],
      },
      {
        id: "c2",
        leadName: "Rafael Mendes",
        company: "Grupo Atlas",
        avatarInitials: "RM",
        lastMessage: "O desconto que vocês oferecem é muito baixo.",
        lastMessageAt: "2026-08-04T21:05:00-03:00",
        channel: "whatsapp",
        status: "needs_attention",
        currentOwner: "closer",
        unreadCount: 2,
        isTyping: null,
        handoff: {
          id: "h1",
          reason: "Cliente pediu desconto acima do permitido (18%).",
          requestedAt: "2026-08-04T21:06:00-03:00",
        },
        opportunity: {
          leadName: "Rafael Mendes",
          company: "Grupo Atlas",
          phone: "+55 21 97777-3344",
          email: "rafael.mendes@grupoatlas.com",
          source: "Indicação",
          temperature: "hot",
          pipelineStage: "Negociação",
          currentOwner: "closer",
          aiSummary:
            "Rafael é Diretor Comercial do Grupo Atlas. Proposta de R$ 48k/ano enviada. Solicitou 18% de desconto (limite automático: 10%). Handoff acionado.",
          nextAction: "Humano decidir desconto ou contra-proposta",
          lastActivity: "Há 3 min",
          timeline: [
            { id: "t1", label: "Lead criado", timestamp: "28/07", done: true },
            { id: "t2", label: "Qualificado", timestamp: "30/07", done: true },
            {
              id: "t3",
              label: "Reunião marcada",
              timestamp: "01/08",
              done: true,
            },
            {
              id: "t4",
              label: "Negociação iniciada",
              timestamp: "04/08",
              done: true,
            },
          ],
        },
        messages: [
          {
            id: "m1",
            sender: "system",
            content: "Closer IA iniciou a negociação.",
            timestamp: "2026-08-04T16:00:00-03:00",
            systemKind: "stage_change",
          },
          {
            id: "m2",
            sender: "ai",
            content:
              "Rafael, enviei a proposta formal no e-mail. O plano anual fica em R$ 48.000 com onboarding incluso. Alguma dúvida?",
            timestamp: "2026-08-04T16:02:00-03:00",
            status: "read",
            agentRole: "closer",
          },
          {
            id: "m3",
            sender: "lead",
            content:
              "Gostei da proposta, mas preciso de pelo menos 18% de desconto para fechar este mês.",
            timestamp: "2026-08-04T20:50:00-03:00",
            status: "read",
          },
          {
            id: "m4",
            sender: "ai",
            content:
              "Consigo chegar a 10% com pagamento anual à vista. Acima disso preciso alinhar com o time comercial. Posso verificar e te retorno em breve?",
            timestamp: "2026-08-04T20:55:00-03:00",
            status: "read",
            agentRole: "closer",
          },
          {
            id: "m5",
            sender: "lead",
            content: "O desconto que vocês oferecem é muito baixo.",
            timestamp: "2026-08-04T21:05:00-03:00",
            status: "delivered",
          },
          {
            id: "m6",
            sender: "system",
            content: "A IA solicitou intervenção humana.",
            timestamp: "2026-08-04T21:06:00-03:00",
            systemKind: "assumed",
          },
        ],
      },
      {
        id: "c3",
        leadName: "Ana Beatriz",
        company: "Studio Luna",
        avatarInitials: "AB",
        lastMessage: "Ok, me chama na semana que vem.",
        lastMessageAt: "2026-08-04T14:20:00-03:00",
        channel: "whatsapp",
        status: "ai_handling",
        currentOwner: "followup",
        unreadCount: 0,
        opportunity: {
          leadName: "Ana Beatriz",
          company: "Studio Luna",
          phone: "+55 31 96666-7788",
          email: "ana@studioluna.com",
          source: "Instagram",
          temperature: "warm",
          pipelineStage: "Follow-up",
          currentOwner: "followup",
          aiSummary:
            "Ana demonstrou interesse, mas pediu para retomar na próxima semana por causa de fechamento de trimestre. Agendada sequência de follow-up.",
          nextAction: "Retomar contato em 11/08",
          lastActivity: "Há 7 h",
          timeline: [
            { id: "t1", label: "Lead criado", timestamp: "02/08", done: true },
            {
              id: "t2",
              label: "Qualificado",
              timestamp: "—",
              done: false,
            },
            {
              id: "t3",
              label: "Reunião marcada",
              timestamp: "—",
              done: false,
            },
            {
              id: "t4",
              label: "Negociação iniciada",
              timestamp: "—",
              done: false,
            },
          ],
        },
        messages: [
          {
            id: "m1",
            sender: "system",
            content: "Follow-up IA assumiu o atendimento.",
            timestamp: "2026-08-04T10:00:00-03:00",
            systemKind: "assumed",
          },
          {
            id: "m2",
            sender: "ai",
            content:
              "Oi Ana! Passando para saber se conseguiu revisar o material que enviei. Qualquer dúvida, estou por aqui.",
            timestamp: "2026-08-04T10:01:00-03:00",
            status: "read",
            agentRole: "followup",
          },
          {
            id: "m3",
            sender: "lead",
            content: "Ok, me chama na semana que vem.",
            timestamp: "2026-08-04T14:20:00-03:00",
            status: "read",
          },
        ],
      },
      {
        id: "c4",
        leadName: "Pedro Oliveira",
        company: "FinTech BR",
        avatarInitials: "PO",
        lastMessage: "Pode me ligar amanhã às 10?",
        lastMessageAt: "2026-08-04T17:30:00-03:00",
        channel: "whatsapp",
        status: "human",
        currentOwner: "human",
        unreadCount: 1,
        opportunity: {
          leadName: "Pedro Oliveira",
          company: "FinTech BR",
          phone: "+55 11 95555-0011",
          email: "pedro@fintechbr.io",
          source: "Evento",
          temperature: "hot",
          pipelineStage: "Discovery",
          currentOwner: "human",
          aiSummary:
            "Pedro pediu contato humano direto. Preferência por ligação. Empresa em expansão, 40 vendedores.",
          nextAction: "Ligar amanhã às 10h",
          lastActivity: "Há 4 h",
          timeline: [
            { id: "t1", label: "Lead criado", timestamp: "04/08", done: true },
            {
              id: "t2",
              label: "Qualificado",
              timestamp: "—",
              done: false,
            },
            {
              id: "t3",
              label: "Reunião marcada",
              timestamp: "—",
              done: false,
            },
            {
              id: "t4",
              label: "Negociação iniciada",
              timestamp: "—",
              done: false,
            },
          ],
        },
        messages: [
          {
            id: "m1",
            sender: "system",
            content: "SDR IA assumiu o atendimento.",
            timestamp: "2026-08-04T15:00:00-03:00",
            systemKind: "assumed",
          },
          {
            id: "m2",
            sender: "ai",
            content:
              "Olá Pedro! Vi que você esteve no evento de ontem. Posso te apresentar como a ForceIA opera um time comercial completo?",
            timestamp: "2026-08-04T15:01:00-03:00",
            status: "read",
            agentRole: "sdr",
          },
          {
            id: "m3",
            sender: "lead",
            content: "Prefiro falar com alguém da equipe. Pode me ligar amanhã às 10?",
            timestamp: "2026-08-04T17:30:00-03:00",
            status: "read",
          },
          {
            id: "m4",
            sender: "system",
            content: "Humano assumiu a conversa.",
            timestamp: "2026-08-04T17:32:00-03:00",
            systemKind: "assumed",
          },
          {
            id: "m5",
            sender: "human",
            content:
              "Pedro, aqui é o João. Perfeito, te ligo amanhã às 10h. Até lá!",
            timestamp: "2026-08-04T17:35:00-03:00",
            status: "delivered",
          },
        ],
      },
      {
        id: "c5",
        leadName: "Carla Souza",
        company: "EducaMais",
        avatarInitials: "CS",
        lastMessage: "Obrigada, vamos seguir com o plano anual.",
        lastMessageAt: "2026-08-03T16:00:00-03:00",
        channel: "email",
        status: "closed",
        currentOwner: "closer",
        opportunity: {
          leadName: "Carla Souza",
          company: "EducaMais",
          phone: "+55 41 94444-2233",
          email: "carla@educamais.com.br",
          source: "Site",
          temperature: "hot",
          pipelineStage: "Fechado",
          currentOwner: "closer",
          aiSummary:
            "Negociação concluída. Plano anual fechado em R$ 36k. Onboarding agendado.",
          nextAction: "Acompanhar onboarding",
          lastActivity: "Ontem",
          timeline: [
            { id: "t1", label: "Lead criado", timestamp: "20/07", done: true },
            { id: "t2", label: "Qualificado", timestamp: "22/07", done: true },
            {
              id: "t3",
              label: "Reunião marcada",
              timestamp: "25/07",
              done: true,
            },
            {
              id: "t4",
              label: "Negociação iniciada",
              timestamp: "28/07",
              done: true,
            },
          ],
        },
        messages: [
          {
            id: "m1",
            sender: "system",
            content: "Closer IA iniciou a negociação.",
            timestamp: "2026-08-03T11:00:00-03:00",
            systemKind: "stage_change",
          },
          {
            id: "m2",
            sender: "ai",
            content:
              "Carla, conforme combinado na call, segue a proposta do plano anual com 12% de desconto.",
            timestamp: "2026-08-03T11:05:00-03:00",
            status: "read",
            agentRole: "closer",
          },
          {
            id: "m3",
            sender: "lead",
            content: "Obrigada, vamos seguir com o plano anual.",
            timestamp: "2026-08-03T16:00:00-03:00",
            status: "read",
          },
          {
            id: "m4",
            sender: "system",
            content: "Conversa marcada como resolvida.",
            timestamp: "2026-08-03T16:05:00-03:00",
            systemKind: "note",
          },
        ],
      },
      {
        id: "c6",
        leadName: "Lucas Ferreira",
        company: "LogiExpress",
        avatarInitials: "LF",
        lastMessage: "Ainda estou analisando internamente.",
        lastMessageAt: "2026-08-04T11:15:00-03:00",
        channel: "whatsapp",
        status: "ai_handling",
        currentOwner: "sdr",
        isTyping: "ai",
        opportunity: {
          leadName: "Lucas Ferreira",
          company: "LogiExpress",
          phone: "+55 19 93333-4455",
          email: "lucas@logiexpress.com.br",
          source: "Google Ads",
          temperature: "warm",
          pipelineStage: "Qualificação",
          currentOwner: "sdr",
          aiSummary:
            "Lucas é Gerente de Operações. Interesse moderado. Pediu tempo para alinhar com diretoria.",
          nextAction: "Follow-up em 48h com case de logística",
          lastActivity: "Há 10 h",
          timeline: [
            { id: "t1", label: "Lead criado", timestamp: "03/08", done: true },
            {
              id: "t2",
              label: "Qualificado",
              timestamp: "—",
              done: false,
            },
            {
              id: "t3",
              label: "Reunião marcada",
              timestamp: "—",
              done: false,
            },
            {
              id: "t4",
              label: "Negociação iniciada",
              timestamp: "—",
              done: false,
            },
          ],
        },
        messages: [
          {
            id: "m1",
            sender: "system",
            content: "SDR IA assumiu o atendimento.",
            timestamp: "2026-08-04T09:00:00-03:00",
            systemKind: "assumed",
          },
          {
            id: "m2",
            sender: "ai",
            content:
              "Olá Lucas! Vi que você visitou a página de soluções para logística. Posso te mostrar como a ForceIA ajuda times comerciais de operações?",
            timestamp: "2026-08-04T09:01:00-03:00",
            status: "read",
            agentRole: "sdr",
          },
          {
            id: "m3",
            sender: "lead",
            content: "Ainda estou analisando internamente.",
            timestamp: "2026-08-04T11:15:00-03:00",
            status: "read",
          },
        ],
      },
    ],
  };
}
